### ISSUE TITLE
The "banned code" list barely does anything

### ISSUE THREAD

**Issue by Mixaz017** [KraXen72/crankshaft#3]
You can just put the code into an obfuscator and make the client think its safe. This can be done with no coding knowledge and basically defeats the whole purpose of the system, while slowing down the loading process of scripts (especially with multiple and/or large scripts files). 
![image](https://user-images.githubusercontent.com/31244102/164464802-ccd3638a-7632-4023-8cdc-5669600c8542.png)
I don't think this system should exist in the first place but this should be discussed.

**Comment by KraXen72** [comment]
it was just a bandaid solution for people not trying to inject tos scripts. one could fork it and remove it if they had malicious intents. am aware it is not really helpful but i forgot that obfuscators can even obfuscate literal strings. it's not that big of a deal since its just a an array filter, but unless you have a better idea, i will remove it since this client strives for maximum Performance.

**Comment by Mixaz017** [comment]
You can think like this:
Script devs are the ones that are making userscripts (obviously). They know how to code and read JS/TS, they know how to circumvent word filters, and will do so if they need to.
Users on the other hand, they often have no idea about coding, cannot read even unobfuscated codes, and will proceed to use untrusted/obfuscated codes even with multiple warnings from the client (unless you add a very spooky popup or something).

So... I think the word filter is rather bloaty.

**Comment by KraXen72** [comment]
okay, decided on removal. feel free to pr any better ideas to possibly mitigate this
